### ISSUE TITLE
Vertical Plugs take up entire page

### ISSUE THREAD

**Issue by viv-codes** [ComputerScienceHouse/csh-plug#9]
![plug1](https://user-images.githubusercontent.com/79525734/154981644-7df65467-9de1-4e24-b000-9e34d873a7be.png)
![plug0](https://user-images.githubusercontent.com/79525734/154981646-6f51039b-18a9-4576-9bc8-1c4003e3a288.png)

**Comment by WillNilges** [comment]
Check again

**Comment by viv-codes** [comment]
Resolved
